### ISSUE TITLE
你好 我遇到了非常奇怪的错误  cudaErrorIllegalAddress（非法内存访问）
我们使用的是 openai  OSS 120b 接入 Hermes 使用时会发生下面的报错，感觉不是偶发性问题

### ISSUE THREAD

**Issue by zw6234336** [eugr/spark-vllm-docker#186]
APIServer pid=156) ERROR 04-13 04:11:15 [async_llm.py:551]     raise self._format_exception(outputs) from None
(APIServer pid=156) ERROR 04-13 04:11:15 [async_llm.py:551] vllm.v1.engine.exceptions.EngineDeadError: EngineCore encountered an issue. See stack trace (above) for the root cause.
(EngineCore_DP0 pid=273)   File "/usr/lib/python3.12/multiprocessing/process.py", line 314, in _bootstrap
(EngineCore_DP0 pid=273)     self.run()
(EngineCore_DP0 pid=273)   File "/usr/lib/python3.12/multiprocessing/process.py", line 108, in run
(EngineCore_DP0 pid=273)     self._target(*self._args, **self._kwargs)
(EngineCore_DP0 pid=273)   File "/usr/local/lib/python3.12/dist-packages/vllm/v1/engine/core.py", line 904, in run_engine_core
(EngineCore_DP0 pid=273)     raise e
(EngineCore_DP0 pid=273)   File "/usr/local/lib/python3.12/dist-packages/vllm/v1/engine/core.py", line 893, in run_engine_core
(EngineCore_DP0 pid=273)     engine_core.run_busy_loop()
(EngineCore_DP0 pid=273)   File "/usr/local/lib/python3.12/dist-packages/vllm/v1/engine/core.py", line 920, in run_busy_loop
(EngineCore_DP0 pid=273)     self._process_engine_step()
(EngineCore_DP0 pid=273)   File "/usr/local/lib/python3.12/dist-packages/vllm/v1/engine/core.py", line 953, in _process_engine_step
(EngineCore_DP0 pid=273)     outputs, model_executed = self.step_fn()
(EngineCore_DP0 pid=273)                               ^^^^^^^^^^^^^^
(EngineCore_DP0 pid=273)   File "/usr/local/lib/python3.12/dist-packages/vllm/v1/engine/core.py", line 451, in step_with_batch_queue
(EngineCore_DP0 pid=273)     model_output = future.result()
(EngineCore_DP0 pid=273)                    ^^^^^^^^^^^^^^^
(EngineCore_DP0 pid=273)   File "/usr/lib/python3.12/concurrent/futures/_base.py", line 449, in result
(EngineCore_DP0 pid=273)     return self.__get_result()
(EngineCore_DP0 pid=273)            ^^^^^^^^^^^^^^^^^^^
(EngineCore_DP0 pid=273)   File "/usr/lib/python3.12/concurrent/futures/_base.py", line 401, in __get_result
(EngineCore_DP0 pid=273)     raise self._exception
(EngineCore_DP0 pid=273)   File "/usr/local/lib/python3.12/dist-packages/vllm/v1/executor/uniproc_executor.py", line 79, in collective_rpc
(EngineCore_DP0 pid=273)     result = run_method(self.driver_worker, method, args, kwargs)
(EngineCore_DP0 pid=273)              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(EngineCore_DP0 pid=273)   File "/usr/local/lib/python3.12/dist-packages/vllm/v1/serial_utils.py", line 461, in run_method
(EngineCore_DP0 pid=273)     return func(*args, **kwargs)
(EngineCore_DP0 pid=273)            ^^^^^^^^^^^^^^^^^^^^^
(EngineCore_DP0 pid=273)   File "/usr/local/lib/python3.12/dist-packages/torch/utils/_contextlib.py", line 124, in decorate_context
(EngineCore_DP0 pid=273)     return func(*args, **kwargs)
(EngineCore_DP0 pid=273)            ^^^^^^^^^^^^^^^^^^^^^
(APIServer pid=156) INFO:     127.0.0.1:42142 - "POST /v1/chat/completions HTTP/1.1" 500 Internal Server Error
(EngineCore_DP0 pid=273)   File "/usr/local/lib/python3.12/dist-packages/vllm/v1/worker/gpu_worker.py", line 565, in sample_tokens
(EngineCore_DP0 pid=273)     return self.model_runner.sample_tokens(grammar_output)
(EngineCore_DP0 pid=273)            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(EngineCore_DP0 pid=273)   File "/usr/local/lib/python3.12/dist-packages/torch/utils/_contextlib.py", line 124, in decorate_context
(EngineCore_DP0 pid=273)     return func(*args, **kwargs)
(EngineCore_DP0 pid=273)            ^^^^^^^^^^^^^^^^^^^^^
(EngineCore_DP0 pid=273)   File "/usr/local/lib/python3.12/dist-packages/vllm/v1/worker/gpu_model_runner.py", line 3525, in sample_tokens
(EngineCore_DP0 pid=273)     async_output = AsyncGPUModelRunnerOutput(
(EngineCore_DP0 pid=273)                    ^^^^^^^^^^^^^^^^^^^^^^^^^^
(EngineCore_DP0 pid=273)   File "/usr/local/lib/python3.12/dist-packages/vllm/v1/worker/gpu_model_runner.py", line 216, in __init__
(EngineCore_DP0 pid=273)     self.sampled_token_ids_cpu = self._sampled_token_ids.to(
(EngineCore_DP0 pid=273)                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^
(EngineCore_DP0 pid=273) torch.AcceleratorError: CUDA error: an illegal memory access was encountered
(EngineCore_DP0 pid=273) Search for `cudaErrorIllegalAddress' in https://docs.nvidia.com/cuda/cuda-runtime-api/group__CUDART__TYPES.html for more information.
(EngineCore_DP0 pid=273) CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
(EngineCore_DP0 pid=273) For debugging consider passing CUDA_LAUNCH_BLOCKING=1
(EngineCore_DP0 pid=273) Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.
(EngineCore_DP0 pid=273) 
[rank0]:[W413 04:11:15.959865372 ProcessGroupNCCL.cpp:1565] Warning: WARNING: destroy_process_group() was not called before program exit, which can leak resources. For more info, please see https://pytorch.org/docs/stable/distributed.html#shutdown (function operator())
(APIServer pid=156) INFO:     127.0.0.1:42152 - "GET /api/v1/models HTTP/1.1" 404 Not Found
(APIServer pid=156) INFO:     127.0.0.1:42152 - "GET /api/tags HTTP/1.1" 404 Not Found
(APIServer pid=156) INFO:     127.0.0.1:42152 - "GET /v1/props HTTP/1.1" 404 Not Found
(APIServer pid=156) INFO:     127.0.0.1:42152 - "GET /props HTTP/1.1" 404 Not Found
(APIServer pid=156) INFO:     127.0.0.1:42152 - "GET /version HTTP/1.1" 200 OK
(APIServer pid=156) INFO:     127.0.0.1:42154 - "GET /api/v1/models HTTP/1.1" 404 Not Found
(APIServer pid=156) INFO:     127.0.0.1:42154 - "GET /api/tags HTTP/1.1" 404 Not Found
(APIServer pid=156) INFO:     127.0.0.1:42154 - "GET /v1/props HTTP/1.1" 404 Not Found
(APIServer pid=156) INFO:     127.0.0.1:42154 - "GET /props HTTP/1.1" 404 Not Found
(APIServer pid=156) INFO:     127.0.0.1:42142 - "POST /v1/chat/completions HTTP/1.1" 500 Internal Server Error
(APIServer pid=156) INFO:     127.0.0.1:42154 - "GET /version HTTP/1.1" 200 OK
(APIServer pid=156) INFO:     127.0.0.1:42170 - "GET /v1/models/google/gemini-3-flash-preview HTTP/1.1" 404 Not Found
(APIServer pid=156) INFO:     127.0.0.1:42170 - "GET /v1/models HTTP/1.1" 200 OK
(APIServer pid=156) INFO:     Shutting down
(APIServer pid=156) INFO:     Waiting for application shutdown.
(APIServer pid=156) INFO:     Application shutdown complete.
(APIServer pid=156) INFO:     Finished server process [156]

Stopping cluster...
Stopping head node (127.0.0.1)...
Cluster stopped.

**Comment by eugr** [comment]
Can you provide the exact command you are launching? And also vLLM version as reported in the logs.

**Comment by devid791** [comment]
Hitting the same cudaErrorIllegalAddress on DGX Spark (GB10, SM121) when MTP is enabled.

Hardware

NVIDIA GB10 Grace Blackwell, 128GB unified memory
Driver 580.142, CUDA 13.2 (container), compute capability 12.1
Ubuntu 24.04, single-node --no-ray
vLLM

0.19.1rc1.dev219+g72ff142c3.d20260412.cu132
Image built from this repo (vllm-node:latest)
Model: Intel/Qwen3.5-122B-A10B-int4-AutoRound (122B MoE, 10B active, INT4 AutoRound)

Launch command (working, no MTP)


vllm serve Intel/Qwen3.5-122B-A10B-int4-AutoRound \
  --served-model-name ALICE-122B-A10B-INT4-AR \
  --port 8001 --host 0.0.0.0 \
  --tokenizer Qwen/Qwen3.5-122B-A10B \
  --max-model-len 131072 \
  --gpu-memory-utilization 0.9 \
  --max-num-batched-tokens 8192 \
  --load-format fastsafetensors \
  --enable-prefix-caching \
  --enable-auto-tool-choice \
  --tool-call-parser qwen3_coder \
  --reasoning-parser qwen3 \
  --trust-remote-code
Stable at ~27 tok/s, 0 errors over 100+ requests.

Adding --speculative-config '{"method":"mtp","num_speculative_tokens":2}' → engine dies with cudaErrorIllegalAddress shortly after first request (same trace as OP).

Possibly related to #187 (MTP + --no-ray parsing). Happy to provide full stack trace / repro script if it helps.

**Comment by eugr** [comment]
It is related to flashinfer_cutlass backend being disabled in vLLM main branch since yesterday, so it uses vllm_cutlass instead which breaks MTP compatibility. The next nightly build will include a patch that reverses that change.

**Comment by devid791** [comment]
Thanks @eugr, great to know the root cause. Looking forward to the next nightly — will rebuild and re-test with MTP enabled. Appreciate the fast turnaround!

👍

**Comment by devid791** [comment]
Thanks again @eugr for the quick fix! Just saw the new prebuilt-vllm-current release (0.19.1rc1.dev374) — downloading now to rebuild our node.

If it would help your testing workflow, I'm happy to validate MTP on our setup once deployed — DGX Spark (GB10), Qwen3.5-122B-A10B-INT4-AutoRound, real production traffic on --no-ray. I can share tok/s numbers, stress test results, or repro any edge case you want checked. Feel free to ping me here or reach out directly (@devid791) if you need a second pair of eyes on SM121-specific issues.

Much appreciated — this project is making the DGX Spark actually usable!

**Comment by devid791** [comment]
<html>
<body>
<p style="white-space: pre-wrap; margin-top: 0.1em; margin-bottom: 0.2em; color: rgb(191, 191, 191); font-family: -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, Roboto, sans-serif; font-size: 13px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">Confirmed fix works on DGX Spark (GB10, SM121). Tested with the new <code style="font-family: monospace; color: rgb(140, 140, 140); background-color: rgb(38, 38, 38); padding: 2px 4px; border-radius: 3px; word-break: break-word; font-size: 0.9em;">prebuilt-vllm-current</code> release (<code style="font-family: monospace; color: rgb(140, 140, 140); background-color: rgb(38, 38, 38); padding: 2px 4px; border-radius: 3px; word-break: break-word; font-size: 0.9em;">0.19.1rc1.dev374+g1174723eb.d20260417.cu132</code>) in our production container.</p><p style="white-space: pre-wrap; margin-top: 0.1em; margin-bottom: 0.2em; color: rgb(191, 191, 191); font-family: -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, Roboto, sans-serif; font-size: 13px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><strong>Setup</strong></p><ul style="padding-inline-start: 2em; color: rgb(191, 191, 191); font-family: -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, Roboto, sans-serif; font-size: 13px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><li>Model:<span> </span><code style="font-family: monospace; color: rgb(140, 140, 140); background-color: rgb(38, 38, 38); padding: 2px 4px; border-radius: 3px; word-break: break-word; font-size: 0.9em;">Intel/Qwen3.5-122B-A10B-int4-AutoRound</code></li><li>MTP enabled:<span> </span><code style="font-family: monospace; color: rgb(140, 140, 140); background-color: rgb(38, 38, 38); padding: 2px 4px; border-radius: 3px; word-break: break-word; font-size: 0.9em;">--speculative-config '{"method":"mtp","num_speculative_tokens":1}'</code></li><li>Single-node,<span> </span><code style="font-family: monospace; color: rgb(140, 140, 140); background-color: rgb(38, 38, 38); padding: 2px 4px; border-radius: 3px; word-break: break-word; font-size: 0.9em;">--no-ray</code>, 131072 context, prefix caching, tool calling</li></ul><p style="white-space: pre-wrap; margin-top: 0.1em; margin-bottom: 0.2em; color: rgb(191, 191, 191); font-family: -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, Roboto, sans-serif; font-size: 13px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><strong>Boot log confirmation</strong></p><div class="codeBlockWrapper_-a7MRw" style="position: relative; margin: 8px 0px; color: rgb(191, 191, 191); font-family: -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, Roboto, sans-serif; font-size: 13px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><button class="copyButton_CEmTFw copyButton_-a7MRw" title="Copy code" aria-label="Copy code to clipboard" style="color: rgb(191, 191, 191); font-family: -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, Roboto, sans-serif; font-size: 13px; background: none 0% 0% / auto repeat scroll padding-box border-box rgb(18, 19, 20); border-color: rgb(42, 43, 44); border-style: solid; border-width: 0.666667px; border-image: none 100% / 1 / 0 stretch; cursor: pointer; opacity: 0; display: flex; border-radius: 4px; justify-content: center; align-items: center; padding: 4px; transition: opacity 0.15s, background 0.15s; position: absolute; top: 4px; right: 4px;"><svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="currentColor" aria-hidden="true" data-slot="icon" class="copyIcon_CEmTFw"><path fill-rule="evenodd" d="M15.988 3.012A2.25 2.25 0 0 1 18 5.25v6.5A2.25 2.25 0 0 1 15.75 14H13.5v-3.379a3 3 0 0 0-.879-2.121l-3.12-3.121a3 3 0 0 0-1.402-.791 2.252 2.252 0 0 1 1.913-1.576A2.25 2.25 0 0 1 12.25 1h1.5a2.25 2.25 0 0 1 2.238 2.012ZM11.5 3.25a.75.75 0 0 1 .75-.75h1.5a.75.75 0 0 1 .75.75v.25h-3v-.25Z" clip-rule="evenodd"></path><path d="M3.5 6A1.5 1.5 0 0 0 2 7.5v9A1.5 1.5 0 0 0 3.5 18h7a1.5 1.5 0 0 0 1.5-1.5v-5.879a1.5 1.5 0 0 0-.44-1.06L8.44 6.439A1.5 1.5 0 0 0 7.378 6H3.5Z"></path></svg></button><pre style="overflow-x: auto; white-space: pre; box-sizing: border-box; border-radius: 4px; max-width: 100%; margin: 0px; padding: 8px;"><code style="font-family: monospace; color: rgb(140, 140, 140); background-color: rgb(38, 38, 38); padding: 0px; border-radius: 3px; word-break: break-word; font-size: 0.9em;">Detected MTP model. Sharing target model embedding weights with the draft model.
Using FlashInfer CUTLASS Unquantized MoE backend
</code></pre></div><p style="white-space: pre-wrap; margin-top: 0.1em; margin-bottom: 0.2em; color: rgb(191, 191, 191); font-family: -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, Roboto, sans-serif; font-size: 13px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><strong>Performance (MTP on vs off)</strong></p>
Test | Pre-fix (no MTP) | Post-fix (MTP=1) | Delta
-- | -- | -- | --
Single request (150 tok) | 27.4 tok/s | 33.1 tok/s avg | +21%
Concurrent 8× (150 tok each) | ~40 tok/s agg (no MTP) | 74 tok/s agg | +85%

<p style="white-space: pre-wrap; margin-top: 0.1em; margin-bottom: 0.2em; color: rgb(191, 191, 191); font-family: -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, Roboto, sans-serif; font-size: 13px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><strong>Spec decode metrics after stress test</strong></p><ul style="padding-inline-start: 2em; color: rgb(191, 191, 191); font-family: -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, Roboto, sans-serif; font-size: 13px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><li><code style="font-family: monospace; color: rgb(140, 140, 140); background-color: rgb(38, 38, 38); padding: 2px 4px; border-radius: 3px; word-break: break-word; font-size: 0.9em;">spec_decode_num_drafts_total</code>: 351</li><li><code style="font-family: monospace; color: rgb(140, 140, 140); background-color: rgb(38, 38, 38); padding: 2px 4px; border-radius: 3px; word-break: break-word; font-size: 0.9em;">spec_decode_num_accepted_tokens_total</code>: 247</li><li>Acceptance rate:<span> </span><strong>70%</strong></li></ul><p style="white-space: pre-wrap; margin-top: 0.1em; margin-bottom: 0.2em; color: rgb(191, 191, 191); font-family: -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, Roboto, sans-serif; font-size: 13px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><strong>Stability</strong></p><ul style="padding-inline-start: 2em; color: rgb(191, 191, 191); font-family: -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, Roboto, sans-serif; font-size: 13px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><li>Zero<span> </span><code style="font-family: monospace; color: rgb(140, 140, 140); background-color: rgb(38, 38, 38); padding: 2px 4px; border-radius: 3px; word-break: break-word; font-size: 0.9em;">cudaErrorIllegalAddress</code><span> </span>across 100+ sequential + concurrent requests</li><li>Container uptime clean, no engine crashes</li></ul><p style="white-space: pre-wrap; margin-top: 0.1em; margin-bottom: 0.2em; color: rgb(191, 191, 191); font-family: -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, Roboto, sans-serif; font-size: 13px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">Thanks again for the fast turnaround, @eugr — this unlocks real throughput on GB10. I'm happy to run further validation on new builds (different <code style="font-family: monospace; color: rgb(140, 140, 140); background-color: rgb(38, 38, 38); padding: 2px 4px; border-radius: 3px; word-break: break-word; font-size: 0.9em;">num_speculative_tokens</code>, edge cases, longer contexts) — feel free to ping here or via <code style="font-family: monospace; color: rgb(140, 140, 140); background-color: rgb(38, 38, 38); padding: 2px 4px; border-radius: 3px; word-break: break-word; font-size: 0.9em;">@devid791</code> if there's anything specific you'd like tested on DGX Spark hardware.</p>
</body>
</html>

**Comment by eugr** [comment]
Closing due to OP inactivity.
