### ISSUE TITLE
FULL CUDA graph capture hangs distributed TP inference on 2026-02-09 build

### ISSUE THREAD

**Issue by Balaxxe** [eugr/spark-vllm-docker#35]
**Description:**

Distributed TP inference with gpt-oss-120b hangs after 1-2 requests on the new 2026-02-09 build (PyTorch 2.10 + Triton 3.6.0). The hang is specific to FULL CUDA graph capture mode.

**Steps to reproduce:**

```bash
./launch-cluster.sh -t vllm-node \
  -n <head_ip>,<worker_ip> \
  --ib-if <head_ib>,<worker_ib> \
  exec vllm serve openai/gpt-oss-120b \
  --port 8000 --host 0.0.0.0 \
  --gpu-memory-utilization 0.70 \
  -tp 2 --distributed-executor-backend ray \
  --max-model-len 131072 \
  --no-enable-prefix-caching \
  --max-num-batched-tokens 8192
```

Send 2-3 chat completion requests. The first 1-2 succeed, then the model freezes mid-generation on a subsequent request. Throughput drops to 0 with 1 req still showing as running. After 300s it crashes with `RayChannelTimeoutError`.

**What I tested:**

- `--enforce-eager` → stable
- `--compilation-config '{"cudagraph_mode":"none"}'` → stable
- `--compilation-config '{"cudagraph_mode":"piecewise"}'` → stable
- `--compilation-config '{"cudagraph_mode":"full"}'` → hangs after 1-2 requests
- Default (`FULL_AND_PIECEWISE`) → hangs after 1-2 requests

The FULL portion of CUDA graph capture is what breaks it. Piecewise alone is fine.

**Environment:**

- 2x DGX Spark (GB10, sm_12x, aarch64)
- TP=2 across nodes via InfiniBand
- DGX OS 7.4.0, kernel 6.17.0-1008-nvidia
- vllm-node image built 2026-02-09 (PyTorch 2.10, Triton 3.6.0)
- vLLM 0.15.2rc1.dev135+g285bab475

**Previous build behavior:**

This did not happen on the previous build. The only changes in the 2026-02-09 build were PyTorch 2.10, Triton 3.6.0, and removal of the fastsafetensors patch.

**Workaround:**

`--compilation-config '{"cudagraph_mode":"piecewise"}'`

---

**Comment by jpbreda** [comment]
Can confirm same problem across multiple models.  Checked out a fresh copy and rebuilt according to readme.  Thanks for the workaround.

**Comment by eugr** [comment]
Are you using wheels build? I'm going to disable it, stock pytorch 2.10 is broken. No such issue when compiled from source.

**Comment by eugr** [comment]
Pushed a new version where wheels build is disabled by default. However, today's bug-a-thon broke vLLM completely after this PR has been merged: http://github.com/vllm-project/vllm/pull/34208

I'm going to rebuild with earlier commit and test the cudagraph thing.

**Comment by eugr** [comment]
@jaim12005  - OK, after two more commits, vLLM is working again.
Just tested with a fresh source build, everything works, I ran a few requests and llama-benchy up to 32768 tokens.

Build:

```bash
./build-and-copy.sh -t vllm-node-20260209 --rebuild-vllm -c
```

Run:

```bash
./launch-cluster.sh -t vllm-node-20260209 \
exec vllm serve openai/gpt-oss-120b  \
       --host 0.0.0.0  \
       --port 8888   \
       --enable-auto-tool-choice  \
       --tool-call-parser=openai  \
       --reasoning-parser=openai_gptoss  \
       --gpu-memory-utilization 0.70  \
       --enable-prefix-caching  \
       --load-format fastsafetensors \
       --distributed-executor-backend ray \
       -tp 2
```

Performance is bleh, because this is not an optimized build, but works as expected:

| model               |            test |              t/s |     peak t/s |   peak t/s (req) |        ttfr (ms) |     est_ppt (ms) |    e2e_ttft (ms) |
|:--------------------|----------------:|-----------------:|-------------:|-----------------:|-----------------:|-----------------:|-----------------:|
| openai/gpt-oss-120b |          pp2048 | 5736.18 ± 451.20 |              |                  |   363.84 ± 29.90 |   359.38 ± 29.90 |   414.31 ± 15.66 |
| openai/gpt-oss-120b |            tg32 |     50.58 ± 0.61 | 52.40 ± 0.64 |     52.40 ± 0.64 |                  |                  |                  |
| openai/gpt-oss-120b |  ctx_pp @ d4096 | 5664.40 ± 367.93 |              |                  |   730.78 ± 49.38 |   726.32 ± 49.38 |   772.57 ± 20.45 |
| openai/gpt-oss-120b |  ctx_tg @ d4096 |     52.11 ± 2.16 | 53.98 ± 2.23 |     53.98 ± 2.23 |                  |                  |                  |
| openai/gpt-oss-120b |  pp2048 @ d4096 |  4440.06 ± 91.66 |              |                  |    465.91 ± 9.65 |    461.45 ± 9.65 |    525.01 ± 4.25 |
| openai/gpt-oss-120b |    tg32 @ d4096 |     50.21 ± 0.42 | 52.01 ± 0.44 |     52.01 ± 0.44 |                  |                  |                  |
| openai/gpt-oss-120b |  ctx_pp @ d8192 |  5441.74 ± 71.83 |              |                  |  1510.12 ± 19.99 |  1505.67 ± 19.99 |   1555.43 ± 5.21 |
| openai/gpt-oss-120b |  ctx_tg @ d8192 |     49.44 ± 0.58 | 51.22 ± 0.60 |     51.22 ± 0.60 |                  |                  |                  |
| openai/gpt-oss-120b |  pp2048 @ d8192 |  3911.79 ± 41.30 |              |                  |    528.06 ± 5.51 |    523.60 ± 5.51 |    592.17 ± 6.22 |
| openai/gpt-oss-120b |    tg32 @ d8192 |     49.13 ± 0.20 | 50.90 ± 0.20 |     50.90 ± 0.20 |                  |                  |                  |
| openai/gpt-oss-120b | ctx_pp @ d16384 |   4751.88 ± 7.81 |              |                  |   3452.37 ± 5.67 |   3447.91 ± 5.67 |   3516.66 ± 7.69 |
| openai/gpt-oss-120b | ctx_tg @ d16384 |     44.96 ± 2.71 | 46.57 ± 2.81 |     46.57 ± 2.81 |                  |                  |                  |
| openai/gpt-oss-120b | pp2048 @ d16384 | 2480.51 ± 866.49 |              |                  |  989.76 ± 457.08 |  985.30 ± 457.08 | 1066.12 ± 461.62 |
| openai/gpt-oss-120b |   tg32 @ d16384 |     46.39 ± 1.22 | 48.08 ± 1.28 |     48.08 ± 1.28 |                  |                  |                  |
| openai/gpt-oss-120b | ctx_pp @ d32768 | 3530.97 ± 248.93 |              |                  | 9333.39 ± 691.60 | 9328.93 ± 691.60 | 9377.56 ± 702.90 |
| openai/gpt-oss-120b | ctx_tg @ d32768 |     43.71 ± 0.69 | 45.28 ± 0.71 |     45.28 ± 0.71 |                  |                  |                  |
| openai/gpt-oss-120b | pp2048 @ d32768 |  2093.82 ± 62.33 |              |                  |   983.43 ± 28.73 |   978.97 ± 28.73 |  1026.40 ± 20.42 |
| openai/gpt-oss-120b |   tg32 @ d32768 |     44.02 ± 0.35 | 45.60 ± 0.37 |     45.60 ± 0.37 |                  |                  |                  |

llama-benchy (0.3.0)
date: 2026-02-10 00:41:31 | latency mode: api

**Comment by jpbreda** [comment]
Thanks @eugr .  Was using wheels, will try your latest.
Stuff is definitely a moving target, vllm, triton, PyTorch, cuda all introducing incompatibilities at different times.

Appreciate you working through it.

**Comment by Balaxxe** [comment]
> [@jaim12005](https://github.com/jaim12005) - OK, after two more commits, vLLM is working again. Just tested with a fresh source build, everything works, I ran a few requests and llama-benchy up to 32768 tokens.
> 
> Build:
> 
> ./build-and-copy.sh -t vllm-node-20260209 --rebuild-vllm -c
> 
> Run:
> 
> ./launch-cluster.sh -t vllm-node-20260209 \
> exec vllm serve openai/gpt-oss-120b  \
>        --host 0.0.0.0  \
>        --port 8888   \
>        --enable-auto-tool-choice  \
>        --tool-call-parser=openai  \
>        --reasoning-parser=openai_gptoss  \
>        --gpu-memory-utilization 0.70  \
>        --enable-prefix-caching  \
>        --load-format fastsafetensors \
>        --distributed-executor-backend ray \
>        -tp 2
> 
> Performance is bleh, because this is not an optimized build, but works as expected:
> model 	test 	t/s 	peak t/s 	peak t/s (req) 	ttfr (ms) 	est_ppt (ms) 	e2e_ttft (ms)
> openai/gpt-oss-120b 	pp2048 	5736.18 ± 451.20 			363.84 ± 29.90 	359.38 ± 29.90 	414.31 ± 15.66
> openai/gpt-oss-120b 	tg32 	50.58 ± 0.61 	52.40 ± 0.64 	52.40 ± 0.64 			
> openai/gpt-oss-120b 	ctx_pp @ d4096 	5664.40 ± 367.93 			730.78 ± 49.38 	726.32 ± 49.38 	772.57 ± 20.45
> openai/gpt-oss-120b 	ctx_tg @ d4096 	52.11 ± 2.16 	53.98 ± 2.23 	53.98 ± 2.23 			
> openai/gpt-oss-120b 	pp2048 @ d4096 	4440.06 ± 91.66 			465.91 ± 9.65 	461.45 ± 9.65 	525.01 ± 4.25
> openai/gpt-oss-120b 	tg32 @ d4096 	50.21 ± 0.42 	52.01 ± 0.44 	52.01 ± 0.44 			
> openai/gpt-oss-120b 	ctx_pp @ d8192 	5441.74 ± 71.83 			1510.12 ± 19.99 	1505.67 ± 19.99 	1555.43 ± 5.21
> openai/gpt-oss-120b 	ctx_tg @ d8192 	49.44 ± 0.58 	51.22 ± 0.60 	51.22 ± 0.60 			
> openai/gpt-oss-120b 	pp2048 @ d8192 	3911.79 ± 41.30 			528.06 ± 5.51 	523.60 ± 5.51 	592.17 ± 6.22
> openai/gpt-oss-120b 	tg32 @ d8192 	49.13 ± 0.20 	50.90 ± 0.20 	50.90 ± 0.20 			
> openai/gpt-oss-120b 	ctx_pp @ d16384 	4751.88 ± 7.81 			3452.37 ± 5.67 	3447.91 ± 5.67 	3516.66 ± 7.69
> openai/gpt-oss-120b 	ctx_tg @ d16384 	44.96 ± 2.71 	46.57 ± 2.81 	46.57 ± 2.81 			
> openai/gpt-oss-120b 	pp2048 @ d16384 	2480.51 ± 866.49 			989.76 ± 457.08 	985.30 ± 457.08 	1066.12 ± 461.62
> openai/gpt-oss-120b 	tg32 @ d16384 	46.39 ± 1.22 	48.08 ± 1.28 	48.08 ± 1.28 			
> openai/gpt-oss-120b 	ctx_pp @ d32768 	3530.97 ± 248.93 			9333.39 ± 691.60 	9328.93 ± 691.60 	9377.56 ± 702.90
> openai/gpt-oss-120b 	ctx_tg @ d32768 	43.71 ± 0.69 	45.28 ± 0.71 	45.28 ± 0.71 			
> openai/gpt-oss-120b 	pp2048 @ d32768 	2093.82 ± 62.33 			983.43 ± 28.73 	978.97 ± 28.73 	1026.40 ± 20.42
> openai/gpt-oss-120b 	tg32 @ d32768 	44.02 ± 0.35 	45.60 ± 0.37 	45.60 ± 0.37 			
> 
> llama-benchy (0.3.0) date: 2026-02-10 00:41:31 | latency mode: api

Yep, works for me.

Thank you!
