### ISSUE TITLE
Question: OOM during cuda graph on medium sized models

### ISSUE THREAD

**Issue by stavinsky** [eugr/spark-vllm-docker#52]
I've noticed that  if I load the model even qwen next sometimes and I don't have cache yet, vllm takes all the memory and more during compilation of graph (it is an assumption), gets OOM killer coming to some processes and fails eventually. Second time startup is almost always successful. 
Is there any parameter to overcome that. May limit concurrent jobs or memory somehow? 
I assume this is not a gpu memory but cpu one used, but if the model is big itself there is no room for compilation. 

I've also noticed that it was not like this on old versions of vllm like 13 or 14.

**Comment by eugr** [comment]
Yes, you can use the new `--non-privileged` and associated memory limits. I also recommend using `-j 8` to limit the number of build jobs. Example: 

```bash
./launch-cluster.sh --non-privileged --mem-limit-gb 80 --shm-size-gb 32 -j 8 exec ....
```

The issue is during torch.compile

**Comment by stavinsky** [comment]
thanks. Will try. 
-j is for build job during containter build?

**Comment by eugr** [comment]
> -j is for build job during containter build?

No, this is runtime parameter for the container itself. torch.compile launches cmake/ninja which will observe this limit as it will be setting environment variables. Currently this number is set to 16 (carryover from build phase).

**Comment by stavinsky** [comment]
Cool that is what I needed. I asked because in readme it only described for build-and-copy.sh
Will be testing tomorrow.

**Comment by eugr** [comment]
Good catch, will add to readme

**Comment by eugr** [comment]
Updated README. Keeping this ticket open for now, please keep me updated on your experience.

**Comment by stavinsky** [comment]
-j works like a charm. memory limitation not always

**Comment by eugr** [comment]
What number did you set `-j` to? I wonder if I should make a new default...

**Comment by stavinsky** [comment]
8 is enough for most my cases but i'm not sure how representative my examples. Could it be a better idea to put some tailored versions to recipes ?

**Comment by eugr** [comment]
Actually, that's a very good idea.
